Add debug statements to display which test frameworks can be loaded
- for loading test framework Class.forName("sbt.testing.Framework", true, loader).getProtectionDomain.getCodeSource.getLocation)
- catch NoClassDefFoundError and see which test framework class is causing it